### ISSUE TITLE
Split module into separate repositories

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-drupal-module#2]
At the moment we have Drupal 7.x and 8.x module in the same repository, and in different directories. I think it would be better if Drupal 7.x and 8.x modules are split into separate repositories.

**Comment by kaittodesk** [comment]
Decided to go with multiple branches instead of managing multiple repositories. Latter can get tedious and hard to maintain in the long run.

**Comment by ghost** [comment]
User docs should be updated to prevent users from installing the wrong version, or could we look into getting it on Drupal.org like #17 suggested?

**Comment by kaittodesk** [comment]
I don't think it is possible to install a wrong version of the module, as both versions have `core` defined in their info file, and that should restrict on which Drupal versions you can install (and run) the module.

Drupal.org is definitely somewhere in the pipeline, but I haven't figured out what the best workflow for managing it and GitHub would be. I would like to keep everything in GitHub, but Drupal.org has the community aspect and if we would like to host this module on Drupal.org we need to use its Git.

I am going to close this issue as module has been split. We can take the Drupal.org discussion up in #17.
